
version: 2

models:
  - name: nested_first_model
    description: "A starter dbt model"
    columns:
      - name: variable
        description: "The primary key for this table"
        tests:
          - unique
          - not_null