version: 2

# sources:
#   - name: fivetran_m1_us
#     tables:      
#       - name: sys.sys_config



# Original

sources:
  - name: fivetran_mysql2_us_sys
    tables:      
      - name: sys_config
