
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: salesforce__contact_enhanced
    description: Each record represents a contact with additional account and owner information.
    columns:
      - name: contact_id
        description: '{{ doc("contact_id") }}'
        tests:
          - unique
          - not_null
      - name: contact_name
        description:  '{{ doc("contact_name") }}'
      - name: account_id
        description: '{{ doc("account_id") }}'
      - name: department
        description: '{{ doc("department") }}'
      - name: contact_description
        description: '{{ doc("contact_description") }}'
      - name: email
        description: '{{ doc("email") }}'
      - name: individual_id
        description: '{{ doc("individual_id") }}'
      - name: contact_is_deleted
        description: '{{ doc("contact_is_deleted") }}'
      - name: last_activity_date
        description: '{{ doc("last_activity_date") }}'
      - name: lead_source
        description: '{{ doc("lead_source") }}'
      - name: mailing_city
        description: '{{ doc("mailing_city") }}'
      - name: mailing_country
        description: '{{ doc("mailing_country") }}'
      - name: mailing_country_code
        description: '{{ doc("mailing_country_code") }}'
      - name: mailing_postal_code
        description: '{{ doc("mailing_postal_code") }}'
      - name: mailing_state
        description: '{{ doc("mailing_state") }}'
      - name: mailing_state_code
        description: '{{ doc("mailing_state_code") }}'
      - name: mailing_street
        description: '{{ doc("mailing_street") }}'
      - name: master_record_id
        description: '{{ doc("master_record_id") }}'
      - name: mobile_phone
        description: '{{ doc("mobile_phone") }}'
      - name: contact_owner_id
        description: '{{ doc("contact_owner_id") }}'
      - name: phone
        description: '{{ doc("phone") }}'
      - name: reports_to_id
        description: '{{ doc("reports_to_id") }}'
      - name: contact_owner_name
        description: '{{ doc("contact_owner_name") }}'
      - name: account_name
        description: '{{ doc("account_name") }}'
      - name: account_number
        description: '{{ doc("account_number") }}'
      - name: account_source
        description: '{{ doc("account_source") }}'
      - name: account_annual_revenue
        description: '{{ doc("account_annual_revenue") }}'
      - name: account_description
        description: '{{ doc("account_description") }}'
      - name: account_industry
        description: '{{ doc("account_industry") }}'
      - name: account_is_deleted
        description: '{{ doc("account_is_deleted") }}'
      - name: account_number_of_employees
        description: '{{ doc("account_number_of_employees") }}'
      - name: account_owner_id
        description: '{{ doc("account_owner_id") }}'
      - name: account_parent_id
        description: '{{ doc("account_parent_id") }}'
      - name: account_rating
        description: '{{ doc("account_rating") }}'
      - name: account_type
        description: '{{ doc("account_type") }}'
       
  - name: s3_model
    description: "s3 model"
    columns:
      - name: _line
        description: "The primary key for this table"       

  - name: model_three
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null